{{- if .Values.resourcedirectory.enabled }}
{{- $rdCert := "/certs" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "plgd-cloud.resourcedirectory.configSecretName" . }}
  namespace: {{ .Release.Namespace }}
stringData:
  {{ .Values.resourcedirectory.config.fileName }}: |
    {{- with .Values.resourcedirectory }}
    log:
      debug: {{ .log.debug }}
    apis:
      grpc:
        address: {{  .apis.grpc.address | default (printf "0.0.0.0:%v" .port) | quote }}
        enforcementPolicy:
          minTime: {{ .apis.grpc.enforcementPolicy.minTime | quote }}
          permitWithoutStream: {{ .apis.grpc.enforcementPolicy.permitWithoutStream }}
        keepAlive:
          maxConnectionIdle: {{ .apis.grpc.keepAlive.maxConnectionIdle }}
          maxConnectionAge: {{ .apis.grpc.keepAlive.maxConnectionAge }}
          maxConnectionAgeGrace: {{ .apis.grpc.keepAlive.maxConnectionAgeGrace }}
          time: {{ .apis.grpc.keepAlive.time }}
          timeout: {{ .apis.grpc.keepAlive.timeout }}
        tls:
          {{- $tls := .apis.grpc.tls }}
          {{- include "plgd-cloud.certificateConfig" (list $ $tls $rdCert ) | indent 8 }}
          clientCertificateRequired: {{ .apis.grpc.tls.clientCertificateRequired }}
        authorization:
          authority:{{ printf " " }}{{ required "resourcedirectory.apis.grpc.authorization.authority or global.authority is required " ( $.Values.global.authority | default .apis.grpc.authorization.authority ) | quote }}
          audience:{{ printf " " }}{{ required "resourcedirectory.apis.grpc.authorization.audience or global.audience is required " ( $.Values.global.audience | default .apis.grpc.authorization.audience ) | quote }}
          http:
            maxIdleConns: {{ .apis.grpc.authorization.http.maxIdleConns }}
            maxConnsPerHost: {{ .apis.grpc.authorization.http.maxIdleConnsPerHost }}
            maxIdleConnsPerHost: {{ .apis.grpc.authorization.http.maxIdleConnsPerHost }}
            idleConnTimeout: {{ .apis.grpc.authorization.http.idleConnTimeout }}
            timeout: {{ .apis.grpc.authorization.http.timeout }}
            tls:
              {{- $grpcTls := .apis.grpc.authorization.http.tls }}
              {{- include "plgd-cloud.certificateConfig" (list $ $grpcTls $rdCert ) | indent 12 }}
              useSystemCAPool: {{ .apis.grpc.authorization.http.tls.useSystemCAPool }}
    clients:
      eventBus:
        goPoolSize: {{ .clients.eventBus.goPoolSize }}
        nats:
          url: {{ printf " " }}{{- include "plgd-cloud.natsUri" (list $ .clients.eventBus.nats.url) | quote }}
          jetstream: {{ .clients.eventBus.nats.jetstream }}
          pendingLimits:
            msgLimit: {{ printf "%v" .clients.eventBus.nats.pendingLimits.msgLimit }}
            bytesLimit: {{ printf "%v" .clients.eventBus.nats.pendingLimits.bytesLimit }}
          tls:
            {{- $natsTls := .clients.eventBus.nats.tls }}
            {{- include "plgd-cloud.certificateConfig" (list $ $natsTls $rdCert ) | indent 10 }}
            useSystemCAPool: {{ .clients.eventBus.nats.tls.useSystemCAPool }}
      eventStore:
        cacheExpiration: {{ .clients.eventStore.cacheExpiration }}
        mongoDB:
          uri:{{ printf " " }}{{- include "plgd-cloud.mongoDBUri" (list $ .clients.eventStore.mongoDB.uri)  | quote }}
          database: {{ .clients.eventStore.mongoDB.database }}
          batchSize: {{ .clients.eventStore.mongoDB.batchSize }}
          maxPoolSize: {{ .clients.eventStore.mongoDB.maxPoolSize }}
          maxConnIdleTime: {{ .clients.eventStore.mongoDB.maxConnIdleTime }}
          tls:
            {{- $mongoTls := .clients.eventStore.mongoDB.tls }}
            {{- include "plgd-cloud.certificateConfig" (list $ $natsTls $rdCert ) | indent 10 }}
            useSystemCAPool: {{ .clients.eventStore.mongoDB.tls.useSystemCAPool }}
      authorizationServer:
        pullFrequency: {{ .clients.authorizationServer.pullFrequency }}
        cacheExpiration: {{ .clients.authorizationServer.cacheExpiration }}
        ownerClaim: {{ .clients.authorizationServer.ownerClaim }}
        grpc:
          {{- $authorizationServer := .clients.authorizationServer.grpc.address }}
          address:{{ printf " " }}{{- include "plgd-cloud.authorizationAddress" (list $ $authorizationServer ) | quote }}
          keepAlive:
            time: {{ .clients.authorizationServer.grpc.keepAlive.timeout }}
            timeout: {{ .clients.authorizationServer.grpc.keepAlive.timeout }}
            permitWithoutStream: {{ .clients.authorizationServer.grpc.keepAlive.permitWithoutStream }}
          tls:
            {{- $authClientTls := .clients.authorizationServer.grpc.tls }}
            {{- include "plgd-cloud.certificateConfig" (list $ $authClientTls $rdCert ) | indent 10 }}
            useSystemCAPool: {{ .clients.authorizationServer.grpc.tls.useSystemCAPool }}
        oauth:
          clientID:{{ printf " " }}{{ required "resourcedirectory.clients.authorizationServer.oauth.clientID or global.authorizationServer.oauth.clientID is required " ( .clients.authorizationServer.oauth.clientID  | default $.Values.global.authorizationServer.oauth.clientID ) | quote }}
          clientSecret:{{ printf " " }}{{ required "resourcedirectory.clients.authorizationServer.oauth.clientSecret or global.authorizationServer.oauth.clientSecret is required " ( .clients.authorizationServer.oauth.clientSecret | default $.Values.global.authorizationServer.oauth.clientSecret ) | quote }}
          {{- if ( .clients.authorizationServer.oauth.scopes | default $.Values.global.authorizationServer.oauth.scopes ) }}
          scopes:
          {{- range  ( .clients.authorizationServer.oauth.scopes | default $.Values.global.authorizationServer.oauth.scopes ) }}
            - {{ . | quote }}
          {{- end }}
          {{- else }}
          scopes: []
          {{- end }}
          tokenURL:{{ printf " " }}{{ required "resourcedirectory.clients.authorizationServer.oauth.tokenURL or global.authorizationServer.oauth.tokenURL is required " ( .clients.authorizationServer.oauth.tokenURL | default $.Values.global.authorizationServer.oauth.tokenURL ) | quote }}
          audience:{{ printf " " }}{{ required "resourcedirectory.clients.authorizationServer.oauth.audience or global.audience is required " ( .clients.authorizationServer.oauth.audience | default $.Values.global.audience ) | quote }}
          verifyServiceTokenFrequency: {{ .clients.authorizationServer.oauth.verifyServiceTokenFrequency }}
          http:
            maxIdleConns: {{ .clients.authorizationServer.oauth.http.maxIdleConns }}
            maxConnsPerHost: {{ .clients.authorizationServer.oauth.http.maxConnsPerHost }}
            maxIdleConnsPerHost: {{ .clients.authorizationServer.oauth.http.maxIdleConnsPerHost }}
            idleConnTimeout: {{ .clients.authorizationServer.oauth.http.idleConnTimeout }}
            timeout: {{ .clients.authorizationServer.oauth.http.timeout }}
            tls:
              {{- $oauthHttpClientTls := .clients.authorizationServer.oauth.http.tls }}
              {{- include "plgd-cloud.certificateConfig" (list $ $oauthHttpClientTls $rdCert ) | indent 12 }}
              useSystemCAPool: {{ .clients.authorizationServer.oauth.http.tls.useSystemCAPool }}
    publicConfiguration:
      caPool: {{ .publicConfiguration.caPool | default "/certs/ca.crt" | quote }}
      deviceAuthorization:
        clientID:{{ printf " " }}{{ required "resourcedirectory.publicConfiguration.deviceAuthorization.clientID or global.device.oauth.clientID is required " ( .publicConfiguration.deviceAuthorization.clientID | default $.Values.global.device.oauth.clientID  ) | quote }}
        {{- if ( .publicConfiguration.deviceAuthorization.scopes | default $.Values.global.device.oauth.scopes ) }}
        scopes:
        {{- range  ( .publicConfiguration.deviceAuthorization.scopes | default $.Values.global.device.oauth.scopes ) }}
          - {{ . | quote }}
        {{- end }}
        {{- else }}
        scopes: []
        {{- end }}
        authority:{{ printf " " }}{{ required "resourcedirectory.publicConfiguration.deviceAuthorization.authority or global.authority is required " ( .publicConfiguration.deviceAuthorization.authority | default $.Values.global.authority ) | quote }}
        audience:{{ printf " " }}{{ required "resourcedirectory.publicConfiguration.deviceAuthorization.audience or global.audienceis required " ( .publicConfiguration.deviceAuthorization.audience | default $.Values.global.audience ) | quote }}
        redirectURL:{{ printf " " }}{{ required "resourcedirectory.publicConfiguration.deviceAuthorization.redirectURL or global.device.oauth.redirectURL is required " ( .publicConfiguration.deviceAuthorization.redirectURL | default $.Values.global.device.oauth.redirectURL ) | quote }}
        http:
          maxIdleConns: {{ .publicConfiguration.deviceAuthorization.http.maxIdleConns }}
          maxConnsPerHost: {{ .publicConfiguration.deviceAuthorization.http.maxConnsPerHost }}
          maxIdleConnsPerHost: {{ .publicConfiguration.deviceAuthorization.http.maxIdleConnsPerHost }}
          idleConnTimeout: {{ .publicConfiguration.deviceAuthorization.http.idleConnTimeout }}
          timeout: {{ .publicConfiguration.deviceAuthorization.http.timeout }}
          tls:
            {{- $deviceCfgTls := .publicConfiguration.deviceAuthorization.http.tls }}
            {{- include "plgd-cloud.certificateConfig" (list $ $deviceCfgTls $rdCert ) | indent 10 }}
            useSystemCAPool: {{ .publicConfiguration.deviceAuthorization.http.tls.useSystemCAPool }}
      tokenURL: {{ required "resourcedirectory.publicConfiguration.tokenURL is required" .publicConfiguration.tokenURL | quote }}
      authorizationURL: {{ required "resourcedirectory.publicConfiguration.authorizationURL is required" .publicConfiguration.authorizationURL | quote }}
      ownerClaim: {{ .publicConfiguration.ownerClaim | default "sub" | quote }}
      signingServerAddress: {{ .publicConfiguration.signingServerAddress | default ( printf "api.%s:443" $.Values.global.dnsName ) | quote }}
      cloudID: {{ .publicConfiguration.cloudID | default $.Values.coapgateway.cloudId | quote }}
      cloudURL: {{ .publicConfiguration.cloudURL | default (printf "coaps+tcp://%s:%v" $.Values.global.dnsName $.Values.coapgateway.port ) | quote }}
      cloudAuthorizationProvider: {{ .publicConfiguration.cloudAuthorizationProvider | default "plgd" | quote }}
  {{- end }}
{{- end }}