{{- if .Values.resourcedirectory.enabled }}
{{- $rdClientCert := "/certs/internal" }}
{{- $rdServiceCert := "/certs/service" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "plgd-cloud.resourcedirectory.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "plgd-cloud.labels" . | nindent 4 }}
    {{- with .Values.resourcedirectory.deploymentLabels }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
  {{- with .Values.resourcedirectory.deploymentAnnotations }}
  annotations:
  {{- . | toYaml | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.resourcedirectory.replicas }}
  selector:
    matchLabels:
      {{- include "plgd-cloud.resourcedirectory.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.resourcedirectory.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "plgd-cloud.resourcedirectory.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.resourcedirectory.initContainers }}
      initContainers:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.resourcedirectory.name }}
          {{- with .Values.resourcedirectory.podSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ include "plgd-cloud.resourcedirectory.image" . | quote }}
          imagePullPolicy: {{ .Values.resourcedirectory.image.pullPolicy }}
          command:
            - "--config"
            - {{  printf "%s/%s" .Values.resourcedirectory.config.mountPath .Values.resourcedirectory.config.fileName | quote }}
          ports:
            - name: grpc
              containerPort: {{ .Values.resourcedirectory.port }}
              protocol: TCP
          {{- with .Values.resourcedirectory.livenessProbe }}
          livenessProbe:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resourcedirectory.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resourcedirectory.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: {{ .Values.resourceaggregate.config.mountPath }}
              name: {{ .Values.resourceaggregate.config.volume }}
            {{- if ( include "plgd-cloud.createInternalCertByCm" . ) }}
            - name: internal-crt
              mountPath: {{ $rdClientCert }}
            {{- end }}
            {{- if ( include "plgd-cloud.resourcedirectory.createServiceCertByCm" . ) }}
            - name: service-crt
              mountPath: {{ $rdServiceCert }}
            {{- end }}
            {{- with .Values.resourcedirectory.extraVolumes }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        {{- if ( include "plgd-cloud.createInternalCertByCm" . ) }}
        - name: internal-crt
          secret:
            secretName: {{ include "plgd-cloud.internalCertName" . }}
        {{- end }}
        {{- if ( include "plgd-cloud.resourcedirectory.createServiceCertByCm" . ) }}
        - name: service-crt
          secret:
            secretName: {{ include "plgd-cloud.resourcedirectory.serviceCertName" . }}
        {{- end }}
        {{- with .Values.resourcedirectory.extraVolumeMounts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.resourcedirectory.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.resourcedirectory.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.resourcedirectory.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
