log:
  level: debug
  encoding: json       # Log format
  stacktrace:
    enabled: false
    level: warn        # Stacktrace level
  encoderConfig:
    timeEncoder: rfc3339nano

apis:
  grpc:
    address: "0.0.0.0:9109"
    reflectedServices:
      - GrpcGateway
    sendMsgSize: 4194304
    recvMsgSize: 4194304
    keepAlive:
      maxConnectionIdle: 0s         # 0s means infinity
      maxConnectionAge: 0s
      maxConnectionAgeGrace: 0s
      time: 2h                      # Keep-alive time
      timeout: 20s                  # Keep-alive timeout
    tls:
      caPool: "/home/luki/git/hub/.tmp/certs/root_ca.crt"
      keyFile: "/home/luki/git/hub/.tmp/certs/http.key"
      certFile: "/home/luki/git/hub/.tmp/certs/http.crt"
      clientCertificateRequired: false
