{{- if and .Values.deviceProvisioningService.enabled .Values.deviceProvisioningService.image.dockerConfigSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-dockerconfig" .Release.Name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "plgd-hub.deviceProvisioningService.labels" $ | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.deviceProvisioningService.image.dockerConfigSecret | b64enc }}
{{- end }}