{{- if .Values.deviceProvisioningService.enabled }}
{{- range $.Values.deviceProvisioningService.enrollmentGroups }}
{{- if .hub }}{{ if .hub.authorization }}{{ if .hub.authorization.provider }}{{ if .hub.authorization.provider.clientSecret }}
apiVersion: v1
kind: Secret
metadata:
  {{ $id := (or .hub.id .hub.hubID .id) }}
  name: {{ printf "hub-oauth-%s" $id }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "plgd-hub.deviceProvisioningService.labels" $ | nindent 4 }}
type: Opaque
data:
  clientsecret: {{ .hub.authorization.provider.clientSecret | b64enc }}
---
{{- end }}{{ end }}{{ end }}{{ end }}
{{- end }}
{{- end }}
