{{- if .Values.deviceProvisioningService.enabled }}
{{- range $.Values.deviceProvisioningService.enrollmentGroups }}
{{- if .hub }}{{ if .hub.caPool }}
apiVersion: v1
kind: Secret
metadata:
  {{ $id := (or .hub.id .hub.hubID .id ) }}
  name: {{ printf "hub-ca-%s" $id }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "plgd-hub.deviceProvisioningService.labels" $ | nindent 4 }}
type: kubernetes.io/tls
data:
  ca.crt: {{ .hub.caPool | b64enc }}
---
{{- end }}{{ end }}
{{- end }}
{{- end }}
