{{- if .Values.deviceProvisioningService.enabled }}
{{- range $.Values.deviceProvisioningService.enrollmentGroups }}
{{ $eg := . }}
{{- if .hubs }}
{{- range .hubs }}
{{ if .caPool }}
apiVersion: v1
kind: Secret
metadata:
  {{ $id := (or .id .hubID $eg.id ) }}
  name: {{ printf "hub-ca-%s" $id }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "plgd-hub.deviceProvisioningService.labels" $ | nindent 4 }}
type: kubernetes.io/tls
data:
  ca.crt: {{ .caPool | b64enc }}
---
{{- end }}{{ end }}{{ end }}
{{- end }}
{{- end }}
