{{- if .Values.deviceProvisioningService.enabled }}
{{- range $.Values.deviceProvisioningService.enrollmentGroups }}
{{- $eg := . }}
{{- if .hubs }}
{{- range .hubs }}
{{ if .authorization }}
{{ if .authorization.provider }}
{{ if .authorization.provider.clientSecret }}
apiVersion: v1
kind: Secret
metadata:
  {{ $id := (or .id .hubID $eg.id ) }}
  name: {{ printf "hub-oauth-%s" $id }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "plgd-hub.deviceProvisioningService.labels" $ | nindent 4 }}
type: Opaque
data:
  clientsecret: {{ .authorization.provider.clientSecret | b64enc }}
---
{{- end }}{{ end }}{{ end }}{{ end }}{{ end }}
{{- end }}
{{- end }}
