{{- if .Values.deviceProvisioningService.enabled }}
{{- range $.Values.deviceProvisioningService.enrollmentGroups }}
{{- if .preSharedKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "psk-%s" .id }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "plgd-hub.deviceProvisioningService.labels" $ | nindent 4 }}
type: Opaque
data:
  psk: {{ .preSharedKey | b64enc }}
---
{{- end }}
{{- end }}
{{- end }}
