{{- if and .Values.deviceProvisioningService.enabled .Values.deviceProvisioningService.rbac.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.deviceProvisioningService.rbac.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "plgd-hub.labels" . | nindent 4 }}
{{- end }}
