{{- if .Values.deviceProvisioningService.enabled }}
{{- range $.Values.deviceProvisioningService.enrollmentGroups }}
{{- if .attestationMechanism }}{{ if .attestationMechanism.x509 }}{{ if .attestationMechanism.x509.certificateChain }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "x509-chain-%s" .id }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "plgd-hub.deviceProvisioningService.labels" $ | nindent 4 }}
type: Opaque
data:
  certificatechain.crt: {{ .attestationMechanism.x509.certificateChain | b64enc }}
---
{{- end }}{{ end }}{{ end }}
{{- end }}
{{- end }}
