apiVersion: v2
name: plgd-hub
description: A Helm chart for plgd-hub

type: application

# Equals to hub version; set during the release by the pipeline
version: 0.1.0

appVersion: vnext

dependencies:
  - name: "nats"
    version: "0.13.1"
    repository: "https://nats-io.github.io/k8s/helm/charts/"
    condition: nats.enabled
  - name: "mongodb"
    version: "10.31.3"
    repository: "https://charts.bitnami.com/bitnami"
    condition: mongodb.enabled
