log:
  level: info
  encoding: json
  stacktrace:
    enabled: false
    level: warn
  encoderConfig:
    timeEncoder: rfc3339nano
apis:
  grpc:
    address: "0.0.0.0:9100"
    enforcementPolicy:
      minTime: 5s
      permitWithoutStream: true
    keepAlive:
      # 0s - means infinity
      maxConnectionIdle: 0s
      # 0s - means infinity
      maxConnectionAge: 0s
      # 0s - means infinity
      maxConnectionAgeGrace: 0s
      time: 2h
      timeout: 20s
    tls:
      caPool: "/secrets/public/rootca.crt"
      keyFile: "/secrets/private/cert.key"
      certFile: "/secrets/private/cert.crt"
      clientCertificateRequired: true
    authorization:
      ownerClaim: "sub"
      authority: ""
      audience: ""
      http:
        maxIdleConns: 16
        maxConnsPerHost: 32
        maxIdleConnsPerHost: 16
        idleConnTimeout: "30s"
        timeout: "10s"
        tls:
          caPool: "/secrets/public/rootca.crt"
          keyFile: "/secrets/private/cert.key"
          certFile: "/secrets/public/cert.crt"
          useSystemCAPool: false
clients:
  openTelemetryCollector:
    grpc:
      enabled: false
      address: ""
      keepAlive:
        time: 10s
        timeout: 20s
        permitWithoutStream: true
      tls:
        caPool: "/secrets/public/rootca.crt"
        keyFile: "/secrets/private/cert.key"
        certFile: "/secrets/public/cert.crt"
        useSystemCAPool: false
signer:
  keyFile: "/secrets/private/intermediateca.key"
  certFile: "/secrets/public/intermediateca.crt"
  validFrom: "now-1h"
  expiresIn: "87600h"
  hubID: ""

