log:
  debug: false
apis:
  grpc:
    address: "0.0.0.0:9100"
    enforcementPolicy:
      minTime: 5s
      permitWithoutStream: true
    keepAlive:
      # 0s - means infinity
      maxConnectionIdle: 0s
      # 0s - means infinity
      maxConnectionAge: 0s
      # 0s - means infinity
      maxConnectionAgeGrace: 0s
      time: 2h
      timeout: 20s
    tls:
      caPool: "/secrets/public/rootca.crt"
      keyFile: "/secrets/private/cert.key"
      certFile: "/secrets/public/cert.crt"
      clientCertificateRequired: true
    authorization:
      authority: ""
      audience: ""
      http:
        maxIdleConns: 16
        maxConnsPerHost: 32
        maxIdleConnsPerHost: 16
        idleConnTimeout: 30s
        timeout: 10s
        tls:
          caPool: "/secrets/public/rootca.crt"
          keyFile: "/secrets/private/cert.key"
          certFile: "/secrets/public/cert.crt"
          useSystemCAPool: false
clients:
  eventBus:
    # number of routines to process events in projection
    goPoolSize: 16
    nats:
      url: ""
      pendingLimits:
        msgLimit: 524288
        bytesLimit: 67108864
      tls:
        caPool: "/secrets/public/rootca.crt"
        keyFile: "/secrets/private/cert.key"
        certFile: "/secrets/public/cert.crt"
        useSystemCAPool: false
  eventStore:
    # expiration time of cached resource in projection
    cacheExpiration: 20m
    mongoDB:
      uri: ""
      database: eventStore
      # limits number of queries in one find request.
      batchSize: 128
      # limits number of connections.
      maxPoolSize: 16
      # close connection when idle time reach the value.
      maxConnIdleTime: 4m0s
      tls:
        caPool: "/secrets/public/rootca.crt"
        keyFile: "/secrets/private/cert.key"
        certFile: "/secrets/public/cert.crt"
        useSystemCAPool: false
  authorizationServer:
    pullFrequency: 15s
    cacheExpiration: 1m
    ownerClaim: sub
    grpc:
      address: ""
      tls:
        caPool: "/secrets/public/rootca.crt"
        keyFile: "/secrets/private/cert.key"
        certFile: "/secrets/public/cert.crt"
        useSystemCAPool: false
      keepAlive:
        time: 10s
        timeout: 20s
        permitWithoutStream: true
    oauth:
      clientID: ""
      clientSecret: ""
      scopes: []
      tokenURL: ""
      audience: ""
      verifyServiceTokenFrequency: 10s
      http:
        maxIdleConns: 16
        maxConnsPerHost: 32
        maxIdleConnsPerHost: 16
        idleConnTimeout: 30s
        timeout: 10s
        tls:
          caPool: "/secrets/public/rootca.crt"
          keyFile: "/secrets/private/cert.key"
          certFile: "/secrets/public/cert.crt"
          useSystemCAPool: false
publicConfiguration:
  caPool: "/secrets/public/rootca.crt"
  tokenURL: ""
  authorizationURL: ""
  ownerClaim: "sub"
  signingServerAddress: ""
  cloudID: ""
  cloudURL: ""
  cloudAuthorizationProvider: "plgd"
  defaultCommandTimeToLive: "0s"