{{- if and .Values.mongodb.enabled .Values.certmanager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mongodb-cm-crt
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "plgd-hub.labels" . | nindent 4 }}
spec:
  secretName: mongodb-cm-crt
  privateKey:
    algorithm: {{ .Values.certmanager.storage.cert.key.algorithm | default .Values.certmanager.internal.cert.key.algorithm | default .Values.certmanager.default.cert.key.algorithm }}
    size: {{ .Values.certmanager.storage.cert.key.size | default .Values.certmanager.internal.cert.key.size | default .Values.certmanager.default.cert.key.size }}
  usages:
    - client auth
    - server auth
  ipAddresses:
    - "127.0.0.1"
  dnsNames:
    - "localhost"
    - "mongodb-headless.{{ .Release.Namespace }}.svc.{{ $.Values.cluster.dns }}"
    - "*.mongodb-headless.{{ .Release.Namespace }}.svc.{{ $.Values.cluster.dns }}"
  {{- if and .Values.mongodb.enabled .Values.certmanager.enabled .Values.mongodb.externalAccess.enabled .Values.mongodb.externalAccess.service }}
    {{- range .Values.mongodb.externalAccess.service.publicNames }}
    - {{ . | quote }}
    {{- end }}
  {{- end }}
  {{- range .Values.mongodb.tls.extraDnsNames }}
    - {{ . | quote }}
  {{- end }}
  duration: {{ .Values.certmanager.storage.cert.duration | default .Values.certmanager.internal.cert.duration | default .Values.certmanager.default.cert.duration }}
  renewBefore: {{ .Values.certmanager.storage.cert.renewBefore | default .Values.certmanager.internal.cert.renewBefore | default .Values.certmanager.default.cert.renewBefore }}
  issuerRef:
    name: {{ .Values.certmanager.storage.issuer.name | default .Values.certmanager.internal.issuer.name | default .Values.certmanager.default.issuer.name }}
    kind: {{ .Values.certmanager.storage.issuer.kind | default .Values.certmanager.internal.issuer.kind | default .Values.certmanager.default.issuer.kind }}
    group: {{ .Values.certmanager.storage.issuer.group  | default .Values.certmanager.internal.issuer.group | default .Values.certmanager.default.issuer.group }}
{{- end }}
