{{- if .Values.httpgateway.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "plgd-hub.httpgateway.fullname" . }}
  namespace: {{ .Release.Namespace }}  
  labels:
    {{- include "plgd-hub.labels" . | nindent 4 }}
    {{- with .Values.httpgateway.service.labels }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
  {{- with .Values.httpgateway.service.annotations }}
  annotations:
  {{- . | toYaml | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.httpgateway.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.httpgateway.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
  {{- include "plgd-hub.httpgateway.selectorLabels" . | nindent 4 }}
{{- end }}