{{- if and  .Values.httpgateway.rbac.enabled .Values.httpgateway.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.httpgateway.rbac.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "plgd-cloud.labels" . | nindent 4 }}
{{- end }}
