{{- if .Values.mockoauthserver.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "plgd-hub.mockoauthserver.fullname" . }}
  namespace: {{ .Release.Namespace }}  
  labels:
    {{- include "plgd-hub.labels" . | nindent 4 }}
    {{- with .Values.mockoauthserver.service.labels }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
  {{- if .Values.mockoauthserver.service.annotations }}
  annotations:
    {{- include "plgd-hub.tplvalues.render" ( dict "value" .Values.mockoauthserver.service.annotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.mockoauthserver.service.type | default "ClusterIP" }}
  ports:
    {{- if .Values.mockoauthserver.service.ports }}
    {{- toYaml .Values.mockoauthserver.service.ports | nindent 4 }}
    {{- else }}
    - port: {{ .Values.mockoauthserver.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- end }}
  selector:
  {{- include "plgd-hub.mockoauthserver.selectorLabels" . | nindent 4 }}
{{- end }}