{{- if .Values.coapgateway.enabled }}
{{- $coapGatewayServiceCert := "/certs" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "plgd-cloud.coapgateway.configSecretName" . }}
  namespace: {{ .Release.Namespace }}
stringData:
  {{ .Values.coapgateway.config.fileName }}: |
    {{- with .Values.coapgateway }}
    log:
      debug: {{ .log.debug }}
      dumpCoapMessages: {{ .log.dumpCoapMessages }}
    apis:
      coap:
        address: {{ printf "0.0.0.0:%v" .port | quote }}
        externalAddress: {{ .apis.coap.externalAddress  | default (printf "%s:%v" $.Values.global.domain $.Values.coapgateway.port ) | quote }}
        maxMessageSize: {{ .apis.coap.maxMessageSize }}
        ownerCacheExpiration: {{ .apis.coap.ownerCacheExpiration }}
        goroutineSocketHeartbeat: {{ .apis.coap.goroutineSocketHeartbeat | quote }}
        keepAlive:
          timeout: {{ .apis.coap.keepAlive.timeout }}
        blockwiseTransfer:
          enabled: {{ .apis.coap.blockwiseTransfer.enabled }}
          blockSize: {{ .apis.coap.blockwiseTransfer.blockSize | quote }}
        tls:
          enabled: {{ .apis.coap.tls.enabled }}
          {{- if .apis.coap.tls.enabled }}
          {{- $tls := .apis.coap.tls }}
          {{- include "plgd-cloud.certificateConfig" (list $ $tls $coapGatewayServiceCert) | indent 8 }}
          clientCertificateRequired: {{ .apis.coap.tls.clientCertificateRequired }}
          {{- end }}
        authorization:
          clientID:{{ printf " " }}{{ required "coapgateway.apis.coap.authorization.clientID or global.oauth.device.clientID is required " (  .apis.coap.authorization.clientID | default $.Values.global.oauth.device.clientID  ) | quote }}
          clientSecret:{{ printf " " }}{{ required "coapgateway.apis.coap.authorization.clientSecret or global.oauth.device.clientSecret is required " ( .apis.coap.authorization.clientSecret | default $.Values.global.oauth.device.clientSecret ) | quote }}
          {{- if ( $.Values.global.oauth.device.scopes | default .apis.coap.authorization.scopes ) }}
          scopes:
          {{- range  ( $.Values.global.oauth.device.scopes | default .apis.coap.authorization.scopes ) }}
            - {{ . | quote }}
          {{- end }}
          {{- else }}
          scopes: []
          {{- end }}
          authority:{{ printf " " }}{{ required "coapgateway.apis.coap.authorization.authority or global.authority is required " ( .apis.coap.authorization.authority | default $.Values.global.authority ) | quote }}
          audience:{{ printf " " }}{{ required "coapgateway.apis.coap.authorization.audience or global.audienceis required " ( .apis.coap.authorization.audience | default $.Values.global.audience ) | quote }}
          redirectURL:{{ printf " " }}{{ required "coapgateway.apis.coap.authorization.redirectURL or global.oauth.device.redirectURL is required " ( .apis.coap.authorization.redirectURL | default $.Values.global.oauth.device.redirectURL ) | quote }}
          http:
            maxIdleConns: {{ .apis.coap.authorization.http.maxIdleConns }}
            maxConnsPerHost: {{ .apis.coap.authorization.http.maxConnsPerHost }}
            maxIdleConnsPerHost: {{ .apis.coap.authorization.http.maxIdleConnsPerHost }}
            idleConnTimeout: {{ .apis.coap.authorization.http.idleConnTimeout }}
            timeout: {{ .apis.coap.authorization.http.timeout }}
            tls:
              {{- $oauthCoapTls := .apis.coap.authorization.http.tls }}
              {{- include "plgd-cloud.certificateConfig" (list $ $oauthCoapTls $coapGatewayServiceCert) | indent 12 }}
              useSystemCAPool: true
    clients:
      eventBus:
        nats:
          url: {{ printf " " }}{{- include "plgd-cloud.natsUri" (list $ .clients.eventBus.nats.url) | quote }}
          pendingLimits:
            msgLimit: {{ .clients.eventBus.nats.pendingLimits.msgLimit }}
            bytesLimit: {{ printf "%v" .clients.eventBus.nats.pendingLimits.bytesLimit }}
          tls:
            {{- $natsTls := .clients.eventBus.nats.tls }}
            {{- include "plgd-cloud.certificateConfig" (list $ $natsTls $coapGatewayServiceCert) | indent 10 }}
            useSystemCAPool: {{ .clients.eventBus.nats.tls.useSystemCAPool }}
      authorizationServer:
        ownerClaim: {{ .clients.authorizationServer.ownerClaim }}
        grpc:
          {{- $authorizationServer := .clients.authorizationServer.grpc.address }}
          address:{{ printf " " }}{{- include "plgd-cloud.authorizationAddress" (list $ $authorizationServer ) | quote }}
          keepAlive:
            time: {{ .clients.authorizationServer.grpc.keepAlive.timeout }}
            timeout: {{ .clients.authorizationServer.grpc.keepAlive.timeout }}
            permitWithoutStream: {{ .clients.authorizationServer.grpc.keepAlive.permitWithoutStream }}
          tls:
            {{- $authClientTls := .clients.authorizationServer.grpc.tls }}
            {{- include "plgd-cloud.certificateConfig" (list $ $authClientTls $coapGatewayServiceCert ) | indent 10 }}
            useSystemCAPool: {{ .clients.authorizationServer.grpc.tls.useSystemCAPool }}
      resourceAggregate:
        grpc:
          {{- $resourceAggregate := .clients.resourceAggregate.grpc.address }}
          address:{{ printf " " }}{{- include "plgd-cloud.resourceAggregateAddress" (list $ $resourceAggregate ) | quote }}
          keepAlive:
            time: {{ .clients.resourceAggregate.grpc.keepAlive.time }}
            timeout: {{ .clients.resourceAggregate.grpc.keepAlive.timeout }}
            permitWithoutStream: {{ .clients.resourceAggregate.grpc.keepAlive.permitWithoutStream }}
          tls:
            {{- $raClientTls := .clients.resourceAggregate.grpc.tls }}
            {{- include "plgd-cloud.certificateConfig" (list $ $raClientTls $coapGatewayServiceCert) | indent 10 }}
            useSystemCAPool: {{ .clients.resourceAggregate.grpc.tls.useSystemCAPool }}
        deviceStatusExpiration:
          enabled: {{ .clients.resourceAggregate.deviceStatusExpiration.enabled }}
          expiresIn: {{ .clients.resourceAggregate.deviceStatusExpiration.expiresIn }}
      resourceDirectory:
        grpc:
          {{- $resourceDirectory := .clients.resourceDirectory.grpc.address }}
          address:{{ printf " " }}{{- include "plgd-cloud.resourceDirectoryAddress" (list $ $resourceDirectory ) | quote }}
          keepAlive:
            time: {{ .clients.resourceDirectory.grpc.keepAlive.time }}
            timeout: {{ .clients.resourceDirectory.grpc.keepAlive.timeout }}
            permitWithoutStream: {{ .clients.resourceDirectory.grpc.keepAlive.permitWithoutStream }}
          tls:
            {{- $rdClientTls := .clients.resourceDirectory.grpc.tls }}
            {{- include "plgd-cloud.certificateConfig" (list $ $rdClientTls $coapGatewayServiceCert) | indent 10 }}
            useSystemCAPool: {{ .clients.resourceDirectory.grpc.tls.useSystemCAPool }}
    taskQueue:
      goPoolSize: {{ .taskQueue.goPoolSize }}
      size: {{ .taskQueue.size }}
      maxIdleTime: {{ .taskQueue.maxIdleTime }}
  {{- end }}
{{- end }}
