{{- $providers := required "At least one oauth provider must be specified for coapgateway.apis.coap.authorization.providers or global.oauth.device" ( $.Values.coapgateway.apis.coap.authorization.providers | default $.Values.global.oauth.device ) }}
{{- range $providers }}
{{- if .clientSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-oauth" .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "plgd-hub.labels" $ | nindent 4 }}
data:
  client-secret: {{ .clientSecret | b64enc }}
---
{{- end }}
{{- end }}