{{- $createServiceCert := include "plgd-cloud.coapgateway.serviceCertName" . }}
{{- if and $createServiceCert .Values.certmanager.enabled .Values.coapgateway.enabled }}
{{- $serviceCertName := include "plgd-cloud.coapgateway.serviceCertName" . }}
{{- $serviceDns := include "plgd-cloud.coapgateway.fullname" . }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $serviceCertName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "plgd-cloud.labels" . | nindent 4 }}
    {{- with .Values.certmanager.coap.labels }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
  {{- with .Values.certmanager.coap.annotations }}
  annotations:
  {{- . | toYaml | nindent 4 }}
  {{- end }}
spec:
  secretName: {{ $serviceCertName }}
  commonName: {{ printf "uuid:%s" (required "coapgateway.cloudId is required parameter" .Values.coapgateway.cloudId ) }}
  privateKey:
    algorithm: {{ .Values.certmanager.coap.cert.key.algorithm | default .Values.certmanager.default.cert.key.algorithm }}
    size: {{ .Values.certmanager.coap.cert.key.size | default .Values.certmanager.default.cert.key.size }}
  usages:
    - server auth
    - client auth
  dnsNames:
    - {{ printf "%s.%s.svc.%s" $serviceDns .Release.Namespace   .Values.cluster.dns }}
  duration: {{ .Values.certmanager.coap.cert.duration | default .Values.certmanager.default.cert.duration }}
  renewBefore: {{ .Values.certmanager.coap.cert.renewBefore | default .Values.certmanager.default.cert.renewBefore }}
  issuerRef:
    name: {{ .Values.certmanager.coap.issuer.name | default .Values.certmanager.default.issuer.name }}
    kind: {{ .Values.certmanager.coap.issuer.kind | default .Values.certmanager.default.issuer.kind }}
    group: cert-manager.io
{{- end }}
