{{- $secretData := .Values.global.m2mOAuthServer.serviceSecret }}
{{- if and $secretData (include "plgd-hub.m2moauthserver.enabled" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.m2moauthserver.serviceSecret.secretName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "plgd-hub.labels" $ | nindent 4 }}
data:
  {{ $.Values.m2moauthserver.serviceSecret.fileName }}: {{ $secretData | b64enc }}
{{- end }}