{{- if .Values.certificateauthority.enabled }}
{{- $fullname := include "plgd-hub.certificateauthority.fullname" . }}
{{- $port := .Values.certificateauthority.httpPort }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullname }}-http
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "plgd-hub.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.certificateauthority.ingress.http.annotations }}
    {{- include "plgd-hub.tplvalues.render" ( dict "value" .Values.certificateauthority.ingress.http.annotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.certificateauthority.ingress.http.customAnnotations }}
    {{- include "plgd-hub.tplvalues.render" ( dict "value" .Values.certificateauthority.ingress.http.customAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  tls:
    - hosts:
        - {{ include "plgd-hub.certificateauthority.domain" . | quote }}
      {{- if $.Values.global.enableWildCartCert }}
      secretName: {{ include "plgd-hub.wildCardCertName" . | quote }}
      {{- else }}
      secretName: {{ include "plgd-hub.certificateauthority.domainCertName" . | quote }}
      {{- end }}
  rules:
  - host: {{ include "plgd-hub.certificateauthority.domain" . | quote }}
    http:
      paths:
      {{- range  .Values.certificateauthority.ingress.http.paths }}
        - path: {{ . }}
          pathType: Prefix
          backend:
            service:
              name: {{ $fullname }}-http
              port:
                number: {{ $port }}
      {{- end }}
{{- end }}
