{{- if and .Values.nats.enabled .Values.certmanager.enabled .Values.nats.config.nats.tls.enabled }}
{{- $natsServiceName := printf "%s-nats" ( include "nats.fullname" . ) }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.nats.config.nats.tls.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "plgd-hub.labels" . | nindent 4 }}
spec:
  secretName: {{ .Values.nats.config.nats.tls.secretName }}
  privateKey:
    algorithm: {{ .Values.certmanager.internal.cert.key.algorithm | default .Values.certmanager.default.cert.key.algorithm }}
    size: {{ .Values.certmanager.internal.cert.key.size | default .Values.certmanager.default.cert.key.size }}
  usages:
    - server auth
  ipAddresses:
    - "127.0.0.1"
  dnsNames:
    - "localhost"
    - "*.{{ .Release.Name }}-nats.{{ .Release.Namespace }}.svc.{{ $.Values.cluster.dns }}"
    - "*.{{ .Release.Namespace }}.pod.{{ $.Values.cluster.dns }}"
    - "{{ .Release.Name }}-nats.{{ .Release.Namespace }}.svc.{{ $.Values.cluster.dns }}"
    - "{{ .Release.Name }}-nats"
  duration: {{ .Values.certmanager.internal.cert.duration | default .Values.certmanager.default.cert.duration }}
  renewBefore: {{ .Values.certmanager.internal.cert.renewBefore | default .Values.certmanager.default.cert.renewBefore }}
  issuerRef:
    name: {{ .Values.certmanager.internal.issuer.name | default .Values.certmanager.default.issuer.name }}
    kind: {{ .Values.certmanager.internal.issuer.kind | default .Values.certmanager.default.issuer.kind }}
    group: {{ .Values.certmanager.internal.issuer.group | default .Values.certmanager.default.issuer.group }}
{{- end }}
