{{- if and ( include "plgd-hub.enableDefaultIssuer" . ) ( $.Values.certmanager.default.ca.issuer.enabled ) }}
apiVersion: cert-manager.io/v1
kind: {{ .Values.certmanager.default.ca.issuer.kind  }}
metadata:
  name: {{ .Values.certmanager.default.ca.issuer.name  }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "plgd-hub.labels" . | nindent 4 }}
  {{- if .Values.certmanager.default.ca.issuer.annotations }}
  annotations:
  {{- range $key, $value := .Values.certmanager.default.ca.issuer.annotations }}
     {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
spec:
{{- if or (and .Values.certmanager.default.ca.issuerRef.name (ne .Values.certmanager.default.ca.issuerRef.name .Values.certmanager.default.ca.issuer.name))
          (and .Values.certmanager.default.ca.issuerRef.kind (ne .Values.certmanager.default.ca.issuerRef.kind .Values.certmanager.default.ca.issuer.kind))}}
  ca:
    secretName: {{ .Values.certmanager.default.ca.secret.name }}
{{- else }}
{{- .Values.certmanager.default.ca.issuer.spec | toYaml | nindent 2 }}
{{- end }}
{{- end }}
