{{- if include "plgd-hub.enableDefaultIssuer" . }}
apiVersion: cert-manager.io/v1
kind: {{ .Values.certmanager.default.issuer.kind  }}
metadata:
  name: {{ .Values.certmanager.default.issuer.name  }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "plgd-hub.labels" . | nindent 4 }}
  {{- if .Values.certmanager.default.issuer.annotations }}
  annotations:
  {{- range $key, $value := .Values.certmanager.default.issuer.annotations }}
     {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
spec:
  ca:
    secretName: {{ .Values.certmanager.default.ca.secret.name }}
{{- end }}