{{- if and ( include "plgd-hub.enableDefaultIssuer" . ) $.Values.certmanager.default.ca.enabled ( $.Values.certmanager.default.ca.issuer.enabled ) }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certmanager.default.ca.secret.name }}
  namespace: {{ .Release.Namespace }}
spec:
  isCA: true
  commonName: {{ .Values.certmanager.default.ca.commonName }}
  secretName: {{ .Values.certmanager.default.ca.secret.name }}
  privateKey:
    algorithm: {{ .Values.certmanager.default.cert.key.algorithm}}
    size: {{ .Values.certmanager.default.cert.key.size }}
  usages:
    - "signing"
    - "crl sign"
  duration: {{ .Values.certmanager.default.cert.duration }}
  renewBefore: {{ .Values.certmanager.default.cert.renewBefore }}
  issuerRef:
    name: {{ .Values.certmanager.default.ca.issuer.name }}
    kind: {{ .Values.certmanager.default.ca.issuer.kind }}
    group: cert-manager.io
{{- end }}