{{- if .Values.identitystore.enabled }}
{{- $cert := "/certs" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "plgd-hub.identitystore.configName" . }}
  namespace: {{ .Release.Namespace }}
data:
  {{ .Values.identitystore.config.fileName }}: |
    {{- with .Values.identitystore }}
    log:
      debug: {{ .log.debug }}
    apis:
      grpc:
        address: {{  .apis.grpc.address | default (printf "0.0.0.0:%v" .port ) | quote }}
        enforcementPolicy:
          minTime: {{ .apis.grpc.enforcementPolicy.minTime | quote }}
          permitWithoutStream: {{ .apis.grpc.enforcementPolicy.permitWithoutStream }}
        keepAlive:
          maxConnectionIdle: {{ .apis.grpc.keepAlive.maxConnectionIdle }}
          maxConnectionAge: {{ .apis.grpc.keepAlive.maxConnectionAge }}
          maxConnectionAgeGrace: {{ .apis.grpc.keepAlive.maxConnectionAgeGrace }}
          time: {{ .apis.grpc.keepAlive.time }}
          timeout: {{ .apis.grpc.keepAlive.timeout }}
        tls:
          {{- $tls := .apis.grpc.tls }}
          {{- include "plgd-hub.certificateConfig" (list $ $tls $cert ) | indent 8 }}
          clientCertificateRequired: {{ .apis.grpc.tls.clientCertificateRequired }}
        authorization:
          {{- $authorization := .apis.grpc.authorization }}
          {{- include "plgd-hub.authorizationConfig" (list $ $authorization "identitystore" ) | indent 8 }}
          http:
            maxIdleConns: {{ .apis.grpc.authorization.http.maxIdleConns }}
            maxConnsPerHost:  {{ .apis.grpc.authorization.http.maxConnsPerHost }}
            maxIdleConnsPerHost:  {{ .apis.grpc.authorization.http.maxIdleConnsPerHost }}
            idleConnTimeout:  {{ .apis.grpc.authorization.http.idleConnTimeout }}
            timeout: {{ .apis.grpc.authorization.http.timeout }}
            tls:
              {{- $httpTls := .apis.grpc.authorization.http.tls }}
              {{- include "plgd-hub.certificateConfig" (list $ $httpTls $cert ) | indent 12 }}
              useSystemCAPool: {{ .apis.grpc.authorization.http.tls.useSystemCAPool }}
    clients:
      eventBus:
        nats:
          url:{{- printf " " }}{{- include "plgd-hub.natsUri" (list $ .clients.eventBus.nats.url )  | quote }}
          jetstream: {{ .clients.eventBus.nats.jetstream }}
          flusherTimeout: {{ .clients.eventBus.nats.flusherTimeout | quote }}
          tls:
            {{- $natsTls := .clients.eventBus.nats.tls }}
            {{- include "plgd-hub.certificateConfig" (list $ $natsTls $cert ) | indent 10 }}
            useSystemCAPool: false
      storage:
        mongoDB:
          uri: {{- printf " " }}{{- include "plgd-hub.mongoDBUri" (list $ .clients.storage.mongoDB.uri )  | quote }}
          database: {{ .clients.storage.mongoDB.database }}
          tls:
            {{- $mongoDbTls := .clients.storage.mongoDB.tls }}
            {{- include "plgd-hub.certificateConfig" (list $ $mongoDbTls $cert ) | indent 10 }}
            useSystemCAPool: {{ .clients.storage.mongoDB.tls.useSystemCAPool }}
  {{- end }}
{{- end }}
