{{- if .Values.grpcgateway.enabled }}
{{- $cert := "/certs" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "plgd-hub.grpcgateway.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "plgd-hub.labels" . | nindent 4 }}
    {{- with .Values.grpcgateway.deploymentLabels }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
  {{- with .Values.grpcgateway.deploymentAnnotations }}
  annotations:
  {{- . | toYaml | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.grpcgateway.replicas }}
  selector:
    matchLabels:
      {{- include "plgd-hub.grpcgateway.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.grpcgateway.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "plgd-hub.grpcgateway.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.grpcgateway.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.grpcgateway.rbac.enabled }}
      serviceAccountName: {{ .Values.grpcgateway.rbac.serviceAccountName }}
      {{- end }}
      {{- with .Values.grpcgateway.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: {{ .Values.grpcgateway.restartPolicy }}
      {{- if .Values.grpcgateway.initContainersTpl }}
      initContainers:
      {{- tpl .Values.grpcgateway.initContainersTpl . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.grpcgateway.name }}
          {{- with .Values.grpcgateway.podSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ include "plgd-hub.grpcgateway.image" . | quote }}
          imagePullPolicy: {{ .Values.grpcgateway.image.pullPolicy }}
          {{- if .Values.grpcgateway.command }}
          command:
          {{- range .Values.grpcgateway.command  }}
            - {{ . | quote }}
          {{- end }}
          {{- end}}
          args:
            - "--config"
            - {{  printf "%s/%s" .Values.grpcgateway.config.mountPath .Values.grpcgateway.config.fileName | quote }}
          ports:
            - name: grpc
              containerPort: {{ .Values.grpcgateway.port }}
              protocol: TCP
          {{- with .Values.grpcgateway.livenessProbe }}
          livenessProbe:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.grpcgateway.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.grpcgateway.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: {{ .Values.grpcgateway.config.mountPath }}
              name: {{ .Values.grpcgateway.config.volume }}
            {{- if ( include "plgd-hub.grpcgateway.createServiceCertByCm" . ) }}
            - name: service-crt
              mountPath: {{ $cert }}
            {{- end }}
            {{- with .Values.grpcgateway.extraVolumes }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - name: {{ .Values.grpcgateway.config.volume }}
          secret:
            secretName: {{ include "plgd-hub.grpcgateway.configSecretName" . }}
        {{- if ( include "plgd-hub.grpcgateway.createServiceCertByCm" . ) }}
        - name: service-crt
          secret:
            secretName: {{ include "plgd-hub.grpcgateway.serviceCertName" . }}
        {{- end }}
        {{- with .Values.grpcgateway.extraVolumeMounts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.grpcgateway.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.grpcgateway.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.grpcgateway.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
