{{- if .Values.grpcgateway.enabled }}
{{- $grpcGatewayCertPath := "/certs" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "plgd-hub.grpcgateway.configName" . }}
  namespace: {{ .Release.Namespace }}
data:
  {{ .Values.grpcgateway.config.fileName }}: |
    {{- with .Values.grpcgateway }}
    log:
      level: {{ .log.level }}
      encoding: {{ .log.encoding }}
      stacktrace:
        enabled: {{ .log.stacktrace.enabled }}
        level: {{ .log.stacktrace.level }}
      encoderConfig:
        timeEncoder: {{ .log.encoderConfig.timeEncoder }}
    apis:
      grpc:
        address: {{ printf "0.0.0.0:%v" .port | quote }}
        sendMsgSize: {{ int64 .apis.grpc.sendMsgSize | default 4194304 }}
        recvMsgSize: {{ int64 .apis.grpc.recvMsgSize | default 4194304 }}
        ownerCacheExpiration: {{ .apis.grpc.ownerCacheExpiration }}
        subscriptionBufferSize: {{ .apis.grpc.subscriptionBufferSize }}
        enforcementPolicy:
          minTime: {{ .apis.grpc.enforcementPolicy.minTime }}
          permitWithoutStream: {{ .apis.grpc.enforcementPolicy.permitWithoutStream }}
        keepAlive:
          # 0s - means infinity
          maxConnectionIdle: {{ .apis.grpc.keepAlive.maxConnectionIdle }}
          # 0s - means infinity
          maxConnectionAge: {{ .apis.grpc.keepAlive.maxConnectionAge }}
          # 0s - means infinity
          maxConnectionAgeGrace: {{ .apis.grpc.keepAlive.maxConnectionAgeGrace }}
          time: {{ .apis.grpc.keepAlive.time }}
          timeout: {{ .apis.grpc.keepAlive.timeout }}
        tls:
          {{- $tls := .apis.grpc.tls }}
          {{- include "plgd-hub.certificateConfig" (list $ $tls $grpcGatewayCertPath) | indent 8 }}
          clientCertificateRequired: {{ .apis.grpc.tls.clientCertificateRequired }}
        authorization:
          {{- $authorization := .apis.grpc.authorization }}
          {{- include "plgd-hub.authorizationConfig" (list $ $authorization "grpcgateway" ) | indent 8 }}
          http:
            maxIdleConns: {{ .apis.grpc.authorization.http.maxIdleConns }}
            maxConnsPerHost: {{ .apis.grpc.authorization.http.maxIdleConnsPerHost }}
            maxIdleConnsPerHost: {{ .apis.grpc.authorization.http.maxIdleConnsPerHost }}
            idleConnTimeout: {{ .apis.grpc.authorization.http.idleConnTimeout }}
            timeout: {{ .apis.grpc.authorization.http.timeout }}
            tls:
              {{- $grpcTls := .apis.grpc.authorization.http.tls }}
              {{- include "plgd-hub.authorizationCaCertificateConfig" (list $ $grpcTls $grpcGatewayCertPath ) | indent 12 }}
              useSystemCAPool: {{ .apis.grpc.authorization.http.tls.useSystemCAPool }}
    clients:
      eventBus:
        goPoolSize: {{ .clients.eventBus.goPoolSize }}
        nats:
          url: {{ printf " " }}{{- include "plgd-hub.natsUri" (list $ .clients.eventBus.nats.url) | quote }}
          pendingLimits:
            msgLimit: {{ .clients.eventBus.nats.pendingLimits.msgLimit }}
            bytesLimit: {{ printf "%v" .clients.eventBus.nats.pendingLimits.bytesLimit }}
          tls:
            {{- $natsTls := .clients.eventBus.nats.tls }}
            {{- include "plgd-hub.certificateConfig" (list $ $natsTls $grpcGatewayCertPath ) | indent 10 }}
            useSystemCAPool: {{ .clients.eventBus.nats.tls.useSystemCAPool }}
      identityStore:
        grpc:
          {{- $authorizationServer := .clients.identityStore.grpc.address }}
          address:{{ printf " " }}{{- include "plgd-hub.identityStoreAddress" (list $ $authorizationServer ) | quote }}
          sendMsgSize: {{ int64 .clients.identityStore.grpc.sendMsgSize | default 4194304 }}
          recvMsgSize: {{ int64 .clients.identityStore.grpc.recvMsgSize | default 4194304 }}
          keepAlive:
            time: {{ .clients.identityStore.grpc.keepAlive.timeout }}
            timeout: {{ .clients.identityStore.grpc.keepAlive.timeout }}
            permitWithoutStream: {{ .clients.identityStore.grpc.keepAlive.permitWithoutStream }}
          tls:
            {{- $authClientTls := .clients.identityStore.grpc.tls }}
            {{- include "plgd-hub.certificateConfig" (list $ $authClientTls $grpcGatewayCertPath ) | indent 10 }}
            useSystemCAPool: {{ .clients.identityStore.grpc.tls.useSystemCAPool }}
      resourceAggregate:
        grpc:
          {{- $resourceAggregate := .clients.resourceAggregate.grpc.address }}
          address:{{ printf " " }}{{- include "plgd-hub.resourceAggregateAddress" (list $ $resourceAggregate ) | quote }}
          sendMsgSize: {{ int64 .clients.resourceAggregate.grpc.sendMsgSize | default 4194304 }}
          recvMsgSize: {{ int64 .clients.resourceAggregate.grpc.recvMsgSize | default 4194304 }}
          keepAlive:
            time: {{ .clients.resourceAggregate.grpc.keepAlive.time }}
            timeout: {{ .clients.resourceAggregate.grpc.keepAlive.timeout }}
            permitWithoutStream: {{ .clients.resourceAggregate.grpc.keepAlive.permitWithoutStream }}
          tls:
            {{- $raClientTls := .clients.resourceAggregate.grpc.tls }}
            {{- include "plgd-hub.certificateConfig" (list $ $raClientTls $grpcGatewayCertPath) | indent 10 }}
            useSystemCAPool: {{ .clients.resourceAggregate.grpc.tls.useSystemCAPool }}
      resourceDirectory:
        grpc:
          {{- $resourceDirectory := .clients.resourceDirectory.grpc.address }}
          address:{{ printf " " }}{{- include "plgd-hub.resourceDirectoryAddress" (list $ $resourceDirectory ) | quote }}
          sendMsgSize: {{ int64 .clients.resourceDirectory.grpc.sendMsgSize | default 4194304 }}
          recvMsgSize: {{ int64 .clients.resourceDirectory.grpc.recvMsgSize | default 4194304 }}
          keepAlive:
            time: {{ .clients.resourceDirectory.grpc.keepAlive.time }}
            timeout: {{ .clients.resourceDirectory.grpc.keepAlive.timeout }}
            permitWithoutStream: {{ .clients.resourceDirectory.grpc.keepAlive.permitWithoutStream }}
          tls:
            {{- $rdClientTls := .clients.resourceDirectory.grpc.tls }}
            {{- include "plgd-hub.certificateConfig" (list $ $rdClientTls $grpcGatewayCertPath ) | indent 10 }}
            useSystemCAPool: {{ .clients.resourceDirectory.grpc.tls.useSystemCAPool }}
      {{- include "plgd-hub.openTelemetryExporterConfig" (list $ $grpcGatewayCertPath) | nindent 6 }}
  {{- end }}
{{- end }}