{{- if .Values.grpcgateway.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "plgd-hub.grpcgateway.fullname" . }}
  namespace: {{ .Release.Namespace }}  
  labels:
    {{- include "plgd-hub.labels" . | nindent 4 }}
    {{- with .Values.grpcgateway.service.labels }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
  {{- if .Values.grpcgateway.service.annotations }}
  annotations:
    {{- include "plgd-hub.tplvalues.render" ( dict "value" .Values.grpcgateway.service.annotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.grpcgateway.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.grpcgateway.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
  {{- include "plgd-hub.grpcgateway.selectorLabels" . | nindent 4 }}
{{- end }}