{{- $createServiceCert := include "plgd-hub.identitystore.serviceCertName" . }}
{{- if and $createServiceCert .Values.certmanager.enabled .Values.identitystore.enabled }}
{{- $serviceDns := include "plgd-hub.identitystore.fullname" . }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $createServiceCert }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "plgd-hub.labels" . | nindent 4 }}
    {{- with .Values.certmanager.internal.labels }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
  {{- with .Values.certmanager.internal.annotations }}
  annotations:
  {{- . | toYaml | nindent 4 }}
  {{- end }}
spec:
  secretName: {{ $createServiceCert }}
  privateKey:
    algorithm: {{ .Values.certmanager.internal.cert.key.algorithm | default .Values.certmanager.default.cert.key.algorithm }}
    size: {{ .Values.certmanager.internal.cert.key.size | default .Values.certmanager.default.cert.key.size }}
  usages:
    - client auth
    - server auth
  dnsNames:
    - {{ printf "%s.%s.svc.%s" $serviceDns .Release.Namespace .Values.cluster.dns }}
    - {{ printf "%s" $serviceDns }}
  duration: {{ .Values.certmanager.internal.cert.duration | default .Values.certmanager.default.cert.duration }}
  renewBefore: {{ .Values.certmanager.internal.cert.renewBefore | default .Values.certmanager.default.cert.renewBefore }}
  issuerRef:
    name: {{ .Values.certmanager.internal.issuer.name | default .Values.certmanager.default.issuer.name }}
    kind: {{ .Values.certmanager.internal.issuer.kind | default .Values.certmanager.default.issuer.kind }}
    group: cert-manager.io
{{- end }}
