{{- if .Values.certificateauthority.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "plgd-hub.certificateauthority.fullname" . }}
  namespace: {{ .Release.Namespace }}  
  labels:
    {{- include "plgd-hub.labels" . | nindent 4 }}
    {{- with .Values.certificateauthority.service.labels }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
  {{- with .Values.certificateauthority.service.annotations }}
  annotations:
  {{- . | toYaml | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.certificateauthority.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.certificateauthority.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
  {{- include "plgd-hub.certificateauthority.selectorLabels" . | nindent 4 }}
{{- end }}