log:
  debug: false
apis:
  grpc:
    ownerCacheExpiration: 1m
    address: "0.0.0.0:9100"
    enforcementPolicy:
      minTime: 5s
      permitWithoutStream: true
    keepAlive:
      # 0s - means infinity
      maxConnectionIdle: 0s
      # 0s - means infinity
      maxConnectionAge: 0s
      # 0s - means infinity
      maxConnectionAgeGrace: 0s
      time: 2h
      timeout: 20s
    tls:
      caPool: "/secrets/public/rootca.crt"
      keyFile: "/secrets/private/cert.key"
      certFile: "/secrets/public/cert.crt"
      clientCertificateRequired: true
    authorization:
      authority: ""
      audience: ""
      http:
        maxIdleConns: 16
        maxConnsPerHost: 32
        maxIdleConnsPerHost: 16
        idleConnTimeout: 30s
        timeout: 10s
        tls:
          caPool: "/secrets/public/rootca.crt"
          keyFile: "/secrets/private/cert.key"
          certFile: "/secrets/public/cert.crt"
          useSystemCAPool: false
clients:
  eventBus:
    nats:
      url: ""
      jetstream: false
      tls:
        caPool: "/secrets/public/rootca.crt"
        keyFile: "/secrets/private/cert.key"
        certFile: "/secrets/public/cert.crt"
        useSystemCAPool: false
  eventStore:
    # replaces time to live in CreateResource, RetrieveResource, UpdateResource, DeleteResource and UpdateDeviceMetadata commands when it is zero value. 0s - means forever.
    defaultCommandTimeToLive: 0s
    # tries to create the snapshot event after n events
    snapshotThreshold: 16
    # limits number of try to store event
    occMaxRetry: 8
    mongoDB:
      uri:
      database: eventStore
      # limits number of queries in one find request.
      batchSize: 128
      # limits number of connections.
      maxPoolSize: 16
      # close connection when idle time reach the value.
      maxConnIdleTime: 4m0s
      tls:
        caPool: "/secrets/public/rootca.crt"
        keyFile: "/secrets/private/cert.key"
        certFile: "/secrets/public/cert.crt"
        useSystemCAPool: false
  authorizationServer:
    ownerClaim: sub
    grpc:
      address: ""
      tls:
        caPool: "/secrets/public/rootca.crt"
        keyFile: "/secrets/private/cert.key"
        certFile: "/secrets/public/cert.crt"
        useSystemCAPool: false
      keepAlive:
        time: 10s
        timeout: 20s
        permitWithoutStream: true
