{{- if and .Values.mongodb.enabled .Values.certmanager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mongodb-cm-crt
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "plgd-cloud.labels" . | nindent 4 }}
spec:
  secretName: mongodb-cm-crt
  privateKey:
    algorithm: {{ .Values.certmanager.internal.cert.key.algorithm | default .Values.certmanager.default.cert.key.algorithm }}
    size: {{ .Values.certmanager.internal.cert.key.size | default .Values.certmanager.default.cert.key.size }}
  usages:
    - client auth
    - server auth
  ipAddresses:
    - "127.0.0.1"
  dnsNames:
    - "localhost"
    - "*.mongodb-headless.{{ .Release.Namespace }}.svc.cluster.local"
  duration: {{ .Values.certmanager.internal.cert.duration | default .Values.certmanager.default.cert.duration }}
  renewBefore: {{ .Values.certmanager.internal.cert.renewBefore | default .Values.certmanager.default.cert.renewBefore }}
  issuerRef:
    name: {{ .Values.certmanager.internal.issuer.name | default .Values.certmanager.default.issuer.name }}
    kind: {{ .Values.certmanager.internal.issuer.kind | default .Values.certmanager.default.issuer.kind }}
    group: cert-manager.io
{{- end }}
