log:
  debug: false
apis:
  http:
    address: "0.0.0.0:9100"
    tls:
      caPool: "/secrets/public/rootca.crt"
      keyFile: "/secrets/private/cert.key"
      certFile: "/secrets/public/cert.crt"
      clientCertificateRequired: true
    eventsURL: ""
    pullDevices:
      disabled: true
      interval: 5s
    authorization:
      clientID: ""
      clientSecretFile: ""
      scopes: []
      authority: ""
      audience: ""
      ownerClaim: "sub"
      redirectURL: ""
      http:
        maxIdleConns: 16
        maxConnsPerHost: 32
        maxIdleConnsPerHost: 16
        idleConnTimeout: 30s
        timeout: 10s
        tls:
          caPool: "/secrets/public/rootca.crt"
          keyFile: "/secrets/private/cert.key"
          certFile: "/secrets/public/cert.crt"
          useSystemCAPool: false
clients:
  identityStore:
    grpc:
      address: ""
      keepAlive:
        time: 10s
        timeout: 20s
        permitWithoutStream: true
      tls:
        caPool: "/secrets/public/rootca.crt"
        keyFile: "/secrets/private/cert.key"
        certFile: "/secrets/public/cert.crt"
        useSystemCAPool: false
  eventBus:
    nats:
      url: ""
      pendingLimits:
        msgLimit: 524288
        bytesLimit: 67108864
      tls:
        caPool: "/secrets/public/rootca.crt"
        keyFile: "/secrets/private/cert.key"
        certFile: "/secrets/public/cert.crt"
        useSystemCAPool: false
  grpcGateway:
    grpc:
      address: ""
      keepAlive:
        time: 10s
        timeout: 20s
        permitWithoutStream: true
      tls:
        caPool: "/secrets/public/rootca.crt"
        keyFile: "/secrets/private/cert.key"
        certFile: "/secrets/public/cert.crt"
        useSystemCAPool: false
  resourceAggregate:
    grpc:
      address: ""
      keepAlive:
        time: 10s
        timeout: 20s
        permitWithoutStream: true
      tls:
        caPool: "/secrets/public/rootca.crt"
        keyFile: "/secrets/private/cert.key"
        certFile: "/secrets/public/cert.crt"
        useSystemCAPool: false
  storage:
    mongoDB:
      uri: "mongodb://localhost:27017"
      database: "cloud2cloudConnector"
      tls:
        caPool: "/secrets/public/rootca.crt"
        keyFile: "/secrets/private/cert.key"
        certFile:  "/secrets/public/cert.crt"
        useSystemCAPool: false
  subscription:
    http:
      reconnectInterval: "10s"
      resubscribeInterval: "10s"
taskProcessor:
  cacheSize: 2048
  timeout: "5s"
  maxParallel: 128
  delay: "0s"
