{{- if and  .Values.snippetservice.rbac.enabled .Values.snippetservice.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.snippetservice.rbac.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "plgd-hub.labels" . | nindent 4 }}
{{- end }}
