log:
  debug: false
  dumpCoapMessages: true
apis:
  coap:
    address: "0.0.0.0:5684"
    externalAddress: ""
    maxMessageSize: 262144
    ownerCacheExpiration: 1m
    subscriptionBufferSize: 1000
    goroutineSocketHeartbeat: "4s"
    keepAlive:
      timeout: 20s
    blockwiseTransfer:
      enabled: false
      blockSize: "1024"
    tls:
      enabled: true
      caPool: "/secrets/public/rootca.crt"
      keyFile: "/secrets/private/cert.key"
      certFile: "/secrets/public/cert.crt"
      clientCertificateRequired: true
    authorization:
      clientID: ""
      clientSecret: ""
      deviceIdClaim: ""
      scopes: []
      authority: ""
      audience: ""
      redirectURL: ""
      http:
        maxIdleConns: 16
        maxConnsPerHost: 32
        maxIdleConnsPerHost: 16
        idleConnTimeout: 30s
        timeout: 10s
        tls:
          caPool: "/secrets/public/rootca.crt"
          keyFile: "/secrets/private/cert.key"
          certFile: "/secrets/public/cert.crt"
          useSystemCAPool: false
clients:
  eventBus:
    nats:
      url: ""
      pendingLimits:
        msgLimit: 524288
        bytesLimit: 67108864
      tls:
        caPool: "/secrets/public/rootca.crt"
        keyFile: "/secrets/private/cert.key"
        certFile: "/secrets/public/cert.crt"
        useSystemCAPool: false
  authorizationServer:
    ownerClaim: sub
    grpc:
      address: ""
      keepAlive:
        time: 10s
        timeout: 20s
        permitWithoutStream: true
      tls:
        caPool: "/secrets/public/rootca.crt"
        keyFile: "/secrets/private/cert.key"
        certFile: "/secrets/public/cert.crt"
        useSystemCAPool: false
  resourceAggregate:
    grpc:
      address: ""
      keepAlive:
        time: 10s
        timeout: 20s
        permitWithoutStream: true
      tls:
        caPool: "/secrets/public/rootca.crt"
        keyFile: "/secrets/private/cert.key"
        certFile: "/secrets/public/cert.crt"
        useSystemCAPool: false
    deviceStatusExpiration:
      enabled: false
      expiresIn: 0s
  resourceDirectory:
    grpc:
      address: ""
      keepAlive:
        time: 10s
        timeout: 20s
        permitWithoutStream: true
      tls:
        caPool: "/secrets/public/rootca.crt"
        keyFile: "/secrets/private/cert.key"
        certFile: "/secrets/public/cert.crt"
        useSystemCAPool: false
taskQueue:
  goPoolSize: 1600
  size: 2097152
  maxIdleTime: "10m"