{{- if .Values.global.authorizationCAPool }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.extraAuthorizationCAPool.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "plgd-hub.labels" $ | nindent 4 }}
data:
  {{ .Values.extraAuthorizationCAPool.fileName }}: {{ .Values.global.authorizationCAPool | b64enc }}
{{- end }}
