{{- if .Values.coapgateway.enabled }}
{{- if (not $.Values.mockoauthserver.enabled)}}
{{- if eq (( $.Values.coapgateway.apis.coap.authorization.providers | default $.Values.global.oauth.device) | len ) 0 }}
{{- fail "At least one oauth provider must be specified for coapgateway.apis.coap.authorization.providers or global.oauth.device" }}
{{- end }}
{{- end }}
{{- $coapGatewayCertPath := "/certs" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "plgd-hub.coapgateway.configName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "plgd-hub.labels" . | nindent 4 }}
data:
  {{ .Values.coapgateway.config.fileName }}: |
    {{- with .Values.coapgateway }}
    log:
      dumpBody: {{ .log.dumpBody }}
      level: {{ .log.level }}
      encoding: {{ .log.encoding }}
      stacktrace:
        enabled: {{ .log.stacktrace.enabled }}
        level: {{ .log.stacktrace.level }}
      encoderConfig:
        timeEncoder: {{ .log.encoderConfig.timeEncoder }}
    apis:
      coap:
        address: {{ printf "0.0.0.0:%v" .port | quote }}
        externalAddress: {{ .apis.coap.externalAddress  | default (printf "%s:%v" $.Values.global.domain $.Values.coapgateway.port ) | quote }}
        maxMessageSize: {{ .apis.coap.maxMessageSize }}
        protocols: 
        {{- range .apis.coap.protocols }}
          - {{ toYaml . | quote }}
        {{- end }}
        ownerCacheExpiration: {{ .apis.coap.ownerCacheExpiration }}
        subscriptionBufferSize:  {{ .apis.coap.subscriptionBufferSize }}
        messagePoolSize: {{ .apis.coap.messagePoolSize }}
        keepAlive:
          timeout: {{ .apis.coap.keepAlive.timeout }}
        blockwiseTransfer:
          enabled: {{ .apis.coap.blockwiseTransfer.enabled }}
          blockSize: {{ .apis.coap.blockwiseTransfer.blockSize | quote }}
        tls:
          enabled: {{ .apis.coap.tls.enabled }}
          disconnectOnExpiredCertificate: {{ .apis.coap.tls.disconnectOnExpiredCertificate }}
          {{- if .apis.coap.tls.enabled }}
          {{- $tls := .apis.coap.tls }}
          {{- include "plgd-hub.certificateConfig" (list $ $tls $coapGatewayCertPath) | indent 8 }}
          clientCertificateRequired: {{ .apis.coap.tls.clientCertificateRequired }}
          {{- end }}
        authorization:
          ownerClaim: {{ .apis.coap.authorization.ownerClaim | default $.Values.global.ownerClaim | quote }}
          {{- if .apis.coap.authorization.deviceIdClaim | default $.Values.global.deviceIdClaim | quote }}
          deviceIDClaim: {{ .apis.coap.authorization.deviceIdClaim | default $.Values.global.deviceIdClaim | quote }}
          {{- end }}
          providers:
          {{- $providers := $.Values.mockoauthserver.oauth }}
          {{- if not $.Values.mockoauthserver.enabled }}
          {{- $providers = required "At least one oauth provider must be specified for coapgateway.apis.coap.authorization.providers or global.oauth.device" ( .apis.coap.authorization.providers | default $.Values.global.oauth.device ) }}
          {{- end }}
          {{- range $providers }}
            - name: {{ required "name for oauth device provider is required" .name | quote }}
              clientID: {{ required "clientID for oauth device provider is required" .clientID | quote }}
              clientSecretFile: {{ include "plgd-hub.oauthSecretFile" (list $ . ) }}
              {{- if .grantType }}
              grantType: {{ .grantType }}
              {{- end }}
              {{- if .scopes }}
              scopes:
              {{- range  .scopes }}
                - {{ toYaml . | quote }}
              {{- end }}
              {{- else }}
              scopes: []
              {{- end }}
              audience: {{ .audience | default $.Values.global.audience | quote }}
              redirectURL: {{ tpl ( required "redirectURL for oauth device provider is required" .redirectURL ) $ | quote }}
              {{- if not $.Values.mockoauthserver.enabled}}
              authority: {{ required "authority for oauth device provider or global.authority is required" ( .authority | default $.Values.global.authority ) | quote }}
              {{- else }}
              authority: {{ include "plgd-hub.mockoauthserver.uri" $ | quote }}
              {{- end }}
              http:
              {{- $http := .http | default dict }}
                maxIdleConns: {{ $http.maxIdleConns | default 16 }}
                maxConnsPerHost: {{ $http.maxConnsPerHost | default 32 }}
                maxIdleConnsPerHost: {{ $http.maxIdleConnsPerHost | default 16 }}
                idleConnTimeout: {{ $http.idleConnTimeout | default "30s" }}
                timeout: {{ $http.timeout | default "10s" }}
                tls:
                  {{- $providerTls := $http.tls }}
                  {{- include "plgd-hub.certificateConfig" (list $ $providerTls $coapGatewayCertPath) | indent 16 }}
                  useSystemCAPool: {{ $providerTls.useSystemCAPool | default true }}
          {{- end }}
    clients:
      eventBus:
        nats:
          url: {{ printf " " }}{{- include "plgd-hub.natsUri" (list $ .clients.eventBus.nats.url) | quote }}
          pendingLimits:
            msgLimit: {{ .clients.eventBus.nats.pendingLimits.msgLimit }}
            bytesLimit: {{ printf "%v" .clients.eventBus.nats.pendingLimits.bytesLimit }}
          tls:
            {{- $natsTls := .clients.eventBus.nats.tls }}
            {{- include "plgd-hub.certificateConfig" (list $ $natsTls $coapGatewayCertPath) | indent 10 }}
            useSystemCAPool: {{ .clients.eventBus.nats.tls.useSystemCAPool }}
      identityStore:
        ownerClaim: {{ .clients.identityStore.ownerClaim | default $.Values.global.ownerClaim | quote }}
        grpc:
          {{- $authorizationServer := .clients.identityStore.grpc.address }}
          address:{{ printf " " }}{{- include "plgd-hub.identityStoreAddress" (list $ $authorizationServer ) | quote }}
          keepAlive:
            time: {{ .clients.identityStore.grpc.keepAlive.time }}
            timeout: {{ .clients.identityStore.grpc.keepAlive.timeout }}
            permitWithoutStream: {{ .clients.identityStore.grpc.keepAlive.permitWithoutStream }}
          tls:
            {{- $authClientTls := .clients.identityStore.grpc.tls }}
            {{- include "plgd-hub.certificateConfig" (list $ $authClientTls $coapGatewayCertPath ) | indent 10 }}
            useSystemCAPool: {{ .clients.identityStore.grpc.tls.useSystemCAPool }}
      resourceAggregate:
        grpc:
          {{- $resourceAggregate := .clients.resourceAggregate.grpc.address }}
          address:{{ printf " " }}{{- include "plgd-hub.resourceAggregateAddress" (list $ $resourceAggregate ) | quote }}
          keepAlive:
            time: {{ .clients.resourceAggregate.grpc.keepAlive.time }}
            timeout: {{ .clients.resourceAggregate.grpc.keepAlive.timeout }}
            permitWithoutStream: {{ .clients.resourceAggregate.grpc.keepAlive.permitWithoutStream }}
          tls:
            {{- $raClientTls := .clients.resourceAggregate.grpc.tls }}
            {{- include "plgd-hub.certificateConfig" (list $ $raClientTls $coapGatewayCertPath) | indent 10 }}
            useSystemCAPool: {{ .clients.resourceAggregate.grpc.tls.useSystemCAPool }}
        deviceStatusExpiration:
          enabled: {{ .clients.resourceAggregate.deviceStatusExpiration.enabled }}
          expiresIn: {{ .clients.resourceAggregate.deviceStatusExpiration.expiresIn }}
      resourceDirectory:
        grpc:
          {{- $resourceDirectory := .clients.resourceDirectory.grpc.address }}
          address:{{ printf " " }}{{- include "plgd-hub.resourceDirectoryAddress" (list $ $resourceDirectory ) | quote }}
          keepAlive:
            time: {{ .clients.resourceDirectory.grpc.keepAlive.time }}
            timeout: {{ .clients.resourceDirectory.grpc.keepAlive.timeout }}
            permitWithoutStream: {{ .clients.resourceDirectory.grpc.keepAlive.permitWithoutStream }}
          tls:
            {{- $rdClientTls := .clients.resourceDirectory.grpc.tls }}
            {{- include "plgd-hub.certificateConfig" (list $ $rdClientTls $coapGatewayCertPath) | indent 10 }}
            useSystemCAPool: {{ .clients.resourceDirectory.grpc.tls.useSystemCAPool }}
      {{- include "plgd-hub.openTelemetryExporterConfig" (list $ $coapGatewayCertPath) | nindent 6 }}
    taskQueue:
      goPoolSize: {{ .taskQueue.goPoolSize }}
      size: {{ .taskQueue.size }}
      maxIdleTime: {{ .taskQueue.maxIdleTime | quote }}
  {{- end }}
{{- end }}
