{{- if .Values.coapgateway.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "plgd-hub.coapgateway.fullname" . }}
  namespace: {{ .Release.Namespace }}  
  labels:
    {{- include "plgd-hub.labels" . | nindent 4 }}
    {{- with .Values.coapgateway.service.labels }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
  {{- if .Values.coapgateway.service.annotations }}
  annotations:
    {{- include "plgd-hub.tplvalues.render" ( dict "value" .Values.coapgateway.service.annotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.coapgateway.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.coapgateway.port }}
      {{- if $.Values.coapgateway.service.nodePort }}
      nodePort: {{ $.Values.coapgateway.service.nodePort }}
      {{- end }}
      targetPort: coaps
      protocol: TCP
      name: coaps
  selector:
  {{- include "plgd-hub.coapgateway.selectorLabels" . | nindent 4 }}
{{- end }}