{{- if .Values.resourceaggregate.enabled }}
{{- $raCert := "/certs" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "plgd-cloud.resourceaggregate.configSecretName" . }}
  namespace: {{ .Release.Namespace }}
stringData:
  {{ .Values.coapgateway.config.fileName }}: |
    {{- with .Values.resourceaggregate }}
    log:
      debug: {{ .log.debug }}
    apis:
      grpc:
        address: {{ printf "0.0.0.0:%v" .port | quote }}
        ownerCacheExpiration: {{ .apis.grpc.ownerCacheExpiration | quote }}
        enforcementPolicy:
          minTime: {{ .apis.grpc.enforcementPolicy.minTime | quote }}
          permitWithoutStream: {{ .apis.grpc.enforcementPolicy.permitWithoutStream }}
        keepAlive:
          maxConnectionIdle: {{ .apis.grpc.keepAlive.maxConnectionIdle }}
          maxConnectionAge: {{ .apis.grpc.keepAlive.maxConnectionAge }}
          maxConnectionAgeGrace: {{ .apis.grpc.keepAlive.maxConnectionAgeGrace }}
          time: {{ .apis.grpc.keepAlive.time }}
          timeout: {{ .apis.grpc.keepAlive.timeout }}
        tls:
          {{- $tls := .apis.grpc.tls }}
          {{- include "plgd-cloud.certificateConfig" (list $ $tls $raCert) | indent 8 }}
          clientCertificateRequired: {{ .apis.grpc.tls.clientCertificateRequired }}
        authorization:
          {{- $authorization := .apis.grpc.authorization }}
          {{- include "plgd-cloud.authorizationConfig" (list $ $authorization "resourceaggregate" ) | indent 8 }}
          http:
            maxIdleConns: {{ .apis.grpc.authorization.http.maxIdleConns }}
            maxConnsPerHost: {{ .apis.grpc.authorization.http.maxIdleConnsPerHost }}
            maxIdleConnsPerHost: {{ .apis.grpc.authorization.http.maxIdleConnsPerHost }}
            idleConnTimeout: {{ .apis.grpc.authorization.http.idleConnTimeout }}
            timeout: {{ .apis.grpc.authorization.http.timeout }}
            tls:
              {{- $grpcTls := .apis.grpc.authorization.http.tls }}
              {{- include "plgd-cloud.certificateConfig" (list $ $grpcTls $raCert) | indent 12 }}
              useSystemCAPool: {{ .apis.grpc.authorization.http.tls.useSystemCAPool }}
    clients:
      eventBus:
        nats:
          url:{{ printf " " }}{{- include "plgd-cloud.natsUri" (list $ .clients.eventBus.nats.url) | quote }}
          jetstream: {{ .clients.eventBus.nats.jetstream }}
          tls:
            {{- $natsTls := .clients.eventBus.nats.tls }}
            {{- include "plgd-cloud.certificateConfig" (list $ $natsTls $raCert) | indent 10 }}
            useSystemCAPool: {{ .clients.eventBus.nats.tls.useSystemCAPool }}
      eventStore:
        defaultCommandTimeToLive: {{ .clients.eventStore.defaultCommandTimeToLive }}
        snapshotThreshold: {{ .clients.eventStore.snapshotThreshold }}
        occMaxRetry: {{ .clients.eventStore.occMaxRetry }}
        mongoDB:
          uri:{{ printf " " }}{{- include "plgd-cloud.mongoDBUri" (list $ .clients.eventStore.mongoDB.uri)  | quote }}
          database: {{ .clients.eventStore.mongoDB.database }}
          batchSize: {{ .clients.eventStore.mongoDB.batchSize }}
          maxPoolSize: {{ .clients.eventStore.mongoDB.maxPoolSize }}
          maxConnIdleTime: {{ .clients.eventStore.mongoDB.maxConnIdleTime }}
          tls:
            {{- $mongoTls := .clients.eventStore.mongoDB.tls }}
            {{- include "plgd-cloud.certificateConfig" (list $ $natsTls $raCert) | indent 10 }}
            useSystemCAPool: {{ .clients.eventStore.mongoDB.tls.useSystemCAPool }}
      identityStore:
        grpc:
          {{- $authorizationServer := .clients.identityStore.grpc.address }}
          address:{{ printf " " }}{{- include "plgd-cloud.identityStoreAddress" (list $ $authorizationServer ) | quote }}
          keepAlive:
            time: {{ .clients.identityStore.grpc.keepAlive.timeout }}
            timeout: {{ .clients.identityStore.grpc.keepAlive.timeout }}
            permitWithoutStream: {{ .clients.identityStore.grpc.keepAlive.permitWithoutStream }}
          tls:
            {{- $authClientTls := .clients.identityStore.grpc.tls }}
            {{- include "plgd-cloud.certificateConfig" (list $ $authClientTls $raCert) | indent 10 }}
            useSystemCAPool: {{ .clients.identityStore.grpc.tls.useSystemCAPool }}
  {{- end }}
{{- end }}
