{{- if and .Values.resourceaggregate.rbac.enabled .Values.resourceaggregate.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.resourceaggregate.rbac.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "plgd-cloud.labels" . | nindent 4 }}
{{- end }}
