{{- $httpGatewayCertPath := "/certs" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "plgd-hub.httpgateway.configName" . }}
  namespace: {{ .Release.Namespace }}
data:
  {{ .Values.httpgateway.config.fileName }}: |
    {{- with .Values.httpgateway }}
    log:
      level: {{ .log.level }}
      encoding: {{ .log.encoding }}
      stacktrace:
        enabled: {{ .log.stacktrace.enabled }}
        level: {{ .log.stacktrace.level }}
      encoderConfig:
        timeEncoder: {{ .log.encoderConfig.timeEncoder }}
    apis:
      http:
        address: {{  .apis.http.address | default (printf "0.0.0.0:%v" .port) | quote }}
        readTimeout: {{ .apis.http.readTimeout }}
        readHeaderTimeout: {{ .apis.http.readHeaderTimeout }}
        writeTimeout: {{ .apis.http.writeTimeout }}
        idleTimeout: {{ .apis.http.idleTimeout }}
        tls:
          {{- $tls := .apis.http.tls }}
          {{- include "plgd-hub.internalCertificateConfig" (list $ $tls $httpGatewayCertPath ) | indent 8 }}
          clientCertificateRequired: {{ .apis.http.tls.clientCertificateRequired }}
        webSocket:
          streamBodyLimit: {{ .apis.http.webSocket.streamBodyLimit }}
          pingFrequency: {{ .apis.http.webSocket.pingFrequency }}
        authorization:
          {{- if not $.Values.mockoauthserver.enabled }}
          authority:{{ printf " " }}{{ required "httpgateway.apis.http.authorization.authority or global.authority is required " ( .apis.http.authorization.authority | default $.Values.global.authority ) | quote }}
          audience:{{ printf " " }}{{ ( .apis.http.authorization.audience | default $.Values.global.audience ) | quote }}
          {{- else }}
          authority:{{ printf " " }}{{ include "plgd-hub.mockoauthserver.uri" $ }}
          audience:{{ printf " " }}{{ printf "" | quote }}
          {{- end }}
          http:
            maxIdleConns: {{ .apis.http.authorization.http.maxIdleConns }}
            maxConnsPerHost: {{ .apis.http.authorization.http.maxIdleConnsPerHost }}
            maxIdleConnsPerHost: {{ .apis.http.authorization.http.maxIdleConnsPerHost }}
            idleConnTimeout: {{ .apis.http.authorization.http.idleConnTimeout }}
            timeout: {{ .apis.http.authorization.http.timeout }}
            tls:
              {{- $httpTls := .apis.http.authorization.http.tls }}
              {{- include "plgd-hub.authorizationCaCertificateConfig" (list $ $httpTls $httpGatewayCertPath ) | indent 12 }}
              useSystemCAPool: {{ .apis.http.authorization.http.tls.useSystemCAPool }}
    clients:
      grpcGateway:
        grpc:
          address: {{ printf " " }}{{- include "plgd-hub.grpcGatewayAddress" (list $ .clients.grpcGateway.grpc.address ) | quote }}
          sendMsgSize: {{ int64 .clients.grpcGateway.grpc.sendMsgSize | default 4194304 }}
          recvMsgSize: {{ int64 .clients.grpcGateway.grpc.recvMsgSize | default 4194304 }}
          keepAlive:
            time: {{ .clients.grpcGateway.grpc.keepAlive.time }}
            timeout: {{ .clients.grpcGateway.grpc.keepAlive.timeout }}
            permitWithoutStream: {{ .clients.grpcGateway.grpc.keepAlive.permitWithoutStream }}
          tls:
            {{- $grpcTls := .clients.grpcGateway.grpc.tls }}
            {{- include "plgd-hub.internalCertificateConfig" (list $ $grpcTls $httpGatewayCertPath ) | indent 10 }}
            useSystemCAPool: {{ .clients.grpcGateway.grpc.tls.useSystemCAPool }}
      {{- include "plgd-hub.openTelemetryExporterConfig" (list $ $httpGatewayCertPath) | nindent 6 }}
    ui:
      enabled: {{ .ui.enabled }}
      {{- if .ui.enabled  }}
      directory: {{ .ui.directory | quote }}
      webConfiguration:
        httpGatewayAddress: {{ .ui.webConfiguration.httpGatewayAddress | default ( printf "https://%s" ( include "plgd-hub.httpgateway.apiDomain" $)) | quote }}
        deviceProvisioningService: {{ .ui.webConfiguration.deviceProvisioningService | default ( include "plgd-hub.httpgateway.dpsApiDomain" $) | quote }}
        snippetService: {{ .ui.webConfiguration.snippetService | default ( include "plgd-hub.httpgateway.snippetServiceApiDomain" $) | quote }}
        {{- if not $.Values.mockoauthserver.enabled }}
        webOAuthClient:
          clientID: {{ required "httpgateway.ui.webConfiguration.webOAuthClient.clientID or global.oauth.web.clientID is required" ( .ui.webConfiguration.webOAuthClient.clientID | default $.Values.global.oauth.web.clientID ) | quote }}
          audience: {{ .ui.webConfiguration.webOAuthClient.audience | default ( $.Values.global.oauth.web.audience | default $.Values.global.audience ) | quote }}
          {{- if .ui.webConfiguration.webOAuthClient.scopes | default $.Values.global.oauth.web.scopes }}
          scopes:
            {{- range .ui.webConfiguration.webOAuthClient.scopes | default $.Values.global.oauth.web.scopes }}
            - {{ . | quote }}
            {{- end }}
          {{- else }}
          scopes: []
          {{- end }}
        {{- else }}
        webOAuthClient:
          {{- $client := index $.Values.mockoauthserver.oauth 1 }}
          clientID: {{ $client.clientID | quote }}
          audience: {{ include "plgd-hub.mockoauthserver.ingressDomain" $ | quote }}
          scopes: [ "openid" ]
        {{- end }}
        deviceOAuthClient:
        {{- $providers := $.Values.mockoauthserver.oauth }}
        {{- if not $.Values.mockoauthserver.enabled }}
        {{- $providers = required "At least one oauth provider must be specified for coapgateway.apis.coap.authorization.providers or global.oauth.device" ( $.Values.coapgateway.apis.coap.authorization.providers | default $.Values.global.oauth.device ) }}
        {{- end }}
        {{- range $providers }}
          {{- if .useInUi }}
          clientID: {{ .clientID | quote }}
          audience: {{ .audience | default $.Values.global.audience | quote }}
          {{- if .scopes }}
          scopes:
          {{- range  .scopes }}
            - {{ toYaml . | quote }}
          {{- end }}
          {{- else }}
          scopes: []
          {{- end }}
          providerName: {{ .name | quote }}
          {{- end }}
        {{- end }}
        visibility:
          mainSidebar:
            certificates : {{ .ui.webConfiguration.visibility.mainSidebar.certificates }}
            chatRoom : {{ .ui.webConfiguration.visibility.mainSidebar.chatRoom }}
            configuration : {{ .ui.webConfiguration.visibility.mainSidebar.configuration }}
            deviceProvisioning : {{ .ui.webConfiguration.visibility.mainSidebar.deviceProvisioning }}
            devices : {{ .ui.webConfiguration.visibility.mainSidebar.devices }}
            docs : {{ .ui.webConfiguration.visibility.mainSidebar.docs }}
            pendingCommands : {{ .ui.webConfiguration.visibility.mainSidebar.pendingCommands }}
            remoteClients : {{ .ui.webConfiguration.visibility.mainSidebar.remoteClients }}
            dashboard : {{ .ui.webConfiguration.visibility.mainSidebar.dashboard }}
            integrations : {{ .ui.webConfiguration.visibility.mainSidebar.integrations }}
            deviceFirmwareUpdate : {{ .ui.webConfiguration.visibility.mainSidebar.deviceFirmwareUpdate }}
            deviceLogs : {{ .ui.webConfiguration.visibility.mainSidebar.deviceLogs }}
            apiTokens : {{ .ui.webConfiguration.visibility.mainSidebar.apiTokens }}
            schemaHub : {{ .ui.webConfiguration.visibility.mainSidebar.schemaHub }}
      {{- end }}
{{- end }}