mode: "standby"
replicaSet:
  standby:
    # List of the MongoDB members in the replica set which are used as backup members
    members: []
    # Set the delay for syncing the standby members with the secondary/primary members
    delaysSeconds: 360
  secondary:
    # Used to configure the secondary members priority
    priority: 10
    # Set number of votes for the secondary members
    votes: 1
    # Set the delay for syncing the secondary members with the primary member
    delaysSeconds: 0
clients:
  storage:
    mongoDB:
      tls:
        # Enable or disable TLS
        enabled: true
        # Path to the CA certificate file
        caPool: "/certs/ca.crt"
        # The certFile and keyFile are the paths to the TLS certificate pair files
        certFile: "/certs/tls.crt"
        keyFile: "/certs/tls.key"
        # Path to the CA certificate file
        useSystemCAPool: false
