{{- if and (include "plgd-hub.mongodb-standby-tool.enabled" .) .Values.mongodb.standbyTool.rbac.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.mongodb.standbyTool.rbac.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "plgd-hub.labels" . | nindent 4 }}
{{- end }}
