# Run special builds that should be supported
name: Builds

on:
  pull_request:
  workflow_dispatch:

jobs:
  builds:
    strategy:
      fail-fast: false
      matrix:
        include:
          # check support for oldest supported golang version
          - name: go1.22
            go-version: "~1.22"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version || '^1.22' }}
          check-latest: true

      - run: |
          go version
          go build ./coap-gateway/cmd/service
