name: Create and publish a docker images to docker.io

on:
  workflow_run:
    workflows:
      - "Test"
    branches:
      - main
    types:
      - completed
  push:
    tags:
      - "*"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  ci:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Set latest tag
        run: echo "RELEASE_VERSION=`echo ${GITHUB_REF#refs/*/} | sed -e 's/main//'`" >> $GITHUB_ENV

      - name: Publish docker images
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin && make push LATEST_TAG=${{ env.RELEASE_VERSION }}
