# Run static analysis checks
name: Static Analysis

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  analysis:
    runs-on: ubuntu-24.04

    steps:
      - name: CPU Info
        run: |
          cat /proc/cpuinfo
          echo "Number of cores: $(nproc)"
          echo "Number of threads: $(nproc --all)"
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "^1.22" # The Go version to download (if necessary) and use.
          check-latest: true
      - run: go version

      - name: Run go vet
        run: go vet ./...

      - name: Check yaml field names and yaml tags
        run: tools/validate/validateYaml.py || echo "invalid yaml field name(s) detected"

      - name: Check json tags
        run: tools/validate/validateJson.py || echo "invalid json tag(s) detected"
