# Run static analysis checks
name: Static Analysis

on:
  pull_request:
    branches:
      - v2

jobs:
  analysis:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Run go vet
        run: go vet ./...

      - name: Install and run ineffassign
        run: |
          export PATH=${PATH}:`go env GOPATH`/bin
          go get github.com/gordonklaus/ineffassign@latest
          ineffassign ./...

      - name: Install and run errcheck
        run: |
          export PATH=${PATH}:`go env GOPATH`/bin
          go get github.com/kisielk/errcheck@latest
          errcheck ./...

      - name: Install and run gocyclo
        run: |
          export PATH=${PATH}:`go env GOPATH`/bin
          go get github.com/fzipp/gocyclo/cmd/gocyclo@latest
          gocyclo -over 15 -ignore ".pb(.gw)?.go$|_test.go$|wsproxy" . || echo "gocyclo detected too complex functions"

      - name: Install and run misspell
        run: |
          # check misspelling in all files in repository
          export PATH=${PATH}:`go env GOPATH`/bin
          go get github.com/client9/misspell/cmd/misspell@latest
          find . -type f -exec misspell {} \;
