# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the action will run. Triggers the workflow push is only on main branch and PR on any branch.
on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test-web-ui:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - name: Prefer IPv4
        run: echo "precedence ::ffff:0:0/96  100" | sudo tee -a /etc/gai.conf
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Run mock hub API
        uses: JarvusInnovations/background-action@v1
        with:
          run: |
            npm install -g husky
            npm install
            npm start &> mock-hub-api.log &
          working-directory: ./http-gateway/web/packages/mock-server
          wait-on: tcp:localhost:8181
          wait-for: 30s
      - name: Run UI server
        uses: JarvusInnovations/background-action@v1
        with:
          run: |
            npm install
            npm run :generate:theme
            npm run build
            REACT_APP_MOCK_BASE_URL=http://localhost:8181 REACT_APP_MOCK_API="true" npm run start &> ui.log &
          working-directory: ./http-gateway/web
          wait-for: 5m
          wait-on: |
            http://localhost:3000
            tcp:localhost:8181
      - name: Run playwright tests
        run: |
          pushd ./http-gateway/web/playwright
          npm install
          npx playwright install --with-deps
          REACT_APP_HTTP_WELL_KNOW_CONFIGURATION_ADDRESS=https://try.plgd.cloud REACT_APP_TEST_LOGIN_USERNAME="$PLAYWRIGHT_USERNAME" REACT_APP_TEST_LOGIN_PASSWORD="$PLAYWRIGHT_PASSWORD" xvfb-run npm run test:dev
          popd
      - name: OnFailure
        if: ${{ failure() }}
        run: |
          cat ./http-gateway/web/packages/mock-server/mock-hub-api.log
          cat ./http-gateway/web/ui.log
      - uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: playwright-report
          path: http-gateway/web/playwright/playwright-report
          retention-days: 5    
