# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the action will run. Triggers the workflow push is only on main branch and PR on any branch.
on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup kernel for multicast messages, increase read buffer to 8MB
        run: sudo sysctl -w net.core.rmem_max=8388608
      
      - name: Get file limit
        run: sudo sysctl fs.file-max

      - name: Get hard ulimits
        run: ulimit -a
    
      - name: Get soft ulimits open files
        run: ulimit -S

      # Runs a single command using the runners shell
      - name: Run a test
        run: make test

      - name: Publish the coverage for main branch
        if: ${{ github.ref == 'refs/heads/main' }}
        run: bash <(curl -s https://codecov.io/bash)
